apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitaly
  namespace: apps-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitaly
  template:
    metadata:
      labels:
        app: orbitaly
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: orbitaly
          image: ghcr.io/levo-studio/orbitaly:latest # {"$imagepolicy": "flux-system:orbitaly"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3017
          env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: orbitaly
  namespace: apps-private
spec:
  type: ClusterIP
  selector:
    app: orbitaly
  ports:
    - name: http
      port: 80
      targetPort: 3017
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitaly
  namespace: apps-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - orbitaly.de
      secretName: orbitaly-de-tls
  rules:
    - host: orbitaly.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orbitaly
                port:
                  number: 80
