name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - "k8s/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    if: "!contains(github.event.head_commit.message, 'Update from image update automation')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/levo-studio/orbitaly:latest
            ghcr.io/levo-studio/orbitaly:${{ github.sha }}
            ghcr.io/levo-studio/orbitaly:build-${{ github.run_number }}
